### ISSUE TITLE
输入过长就报错

### ISSUE THREAD

**Issue by ailfreedom** [huchenlei/ComfyUI_omost#19]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
!!! Exception during processing!!!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\omost_nodes.py", line 429, in layout_cond
    cond: ComfyUIConditioning = self.encode_bag_of_subprompts_greedy(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\omost_nodes.py", line 348, in encode_bag_of_subprompts_greedy
    encoder_output = encode_bag_of_subprompts_greedy(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\lib_omost\greedy_encode.py", line 118, in encode_bag_of_subprompts_greedy
    suffix_targets: list[CLIPTokens] = [
                                       ^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\lib_omost\greedy_encode.py", line 119, in <listcomp>
    tokenize_func(subprompt) for subprompt in suffixes
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\omost_nodes.py", line 336, in tokenize
    clip_l_tokens=convert_comfy_tokens(tokens["l"]),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_omost\omost_nodes.py", line 317, in convert_comfy_tokens
    assert len(comfy_tokens) == 1
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
删除一部分就可以出图

**Comment by huchenlei** [comment]
Already fixed in https://github.com/huchenlei/ComfyUI_omost/pull/17. Please update.
