### ISSUE TITLE
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by wildage** [huchenlei/ComfyUI_omost#24]
how can i deal with this issue?
here are more console logs below:

[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
!!! Exception during processing!!! Only Tensors of floating point and complex dtype can require gradients
Traceback (most recent call last):
  File "C:\stable-diffusion-ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\stable-diffusion-ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\stable-diffusion-ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\stable-diffusion-ComfyUI\custom_nodes\ComfyUI_omost\omost_nodes.py", line 99, in load_llm
    llm_model = AutoModelForCausalLM.from_pretrained(
  File "C:\stable-diffusion-ComfyUI\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "C:\stable-diffusion-ComfyUI\python\lib\site-packages\transformers\modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\stable-diffusion-ComfyUI\python\lib\site-packages\transformers\modeling_utils.py", line 4116, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "C:\stable-diffusion-ComfyUI\python\lib\site-packages\transformers\modeling_utils.py", line 786, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "C:\stable-diffusion-ComfyUI\python\lib\site-packages\transformers\integrations\bitsandbytes.py", line 115, in set_module_quantized_tensor_to_device
    new_value = nn.Parameter(new_value, requires_grad=old_value.requires_grad)
  File "C:\stable-diffusion-ComfyUI\python\lib\site-packages\torch\nn\parameter.py", line 40, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

**Comment by DYSHEJI** [comment]
me too！！

**Comment by Juddddddd** [comment]
pip install transformers>=4.41.1

**Comment by wildage** [comment]
> pip install transformers>=4.41.1

this really helped me, thank you very much!!
