### ISSUE TITLE
Hope mac arm support

### ISSUE THREAD

**Issue by alexcc4** [huchenlei/ComfyUI_omost#37]
```
got prompt
!!! Exception during processing!!! No GPU found. A GPU is needed for quantization.
Traceback (most recent call last):
  File "/Users/liangbinsi/Documents/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/liangbinsi/Documents/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/liangbinsi/Documents/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/liangbinsi/Documents/ComfyUI/custom_nodes/ComfyUI_omost/omost_nodes.py", line 112, in load_llm
    llm_model = AutoModelForCausalLM.from_pretrained(
  File "/Users/liangbinsi/.pyenv/versions/3.10.0/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/liangbinsi/.pyenv/versions/3.10.0/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3202, in from_pretrained
    hf_quantizer.validate_environment(
  File "/Users/liangbinsi/.pyenv/versions/3.10.0/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 62, in validate_environment
    raise RuntimeError("No GPU found. A GPU is needed for quantization.")
RuntimeError: No GPU found. A GPU is needed for quantization.
```

**device: Mac arm64 M3Pro**

**Comment by chingakushin** [comment]
same
