### ISSUE TITLE
Could you update a installation......?

### ISSUE THREAD

**Issue by K-O-N-B** [huchenlei/ComfyUI_omost#47]
don't know how to install it step by step...

**Comment by DevopsDood** [comment]
Updating git repository ComfyUI_omost
Updated git repository ComfyUI_omost
Requirement already satisfied: transformers>=4.41.1 in ./venv/lib/python3.10/site-packages (4.41.2)
ERROR: Could not find a version that satisfies the requirement bitsandbytes>=0.43.1 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes>=0.43.1
Error: StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 1: 'Requirement already satisfied: transformers>=4.41.1 in ./venv/lib/python3.10/site-packages (4.41.2)\nERROR: Could not find a version that satisfies the requirement bitsandbytes>=0.43.1 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)\nERROR: No matching distribution found for bitsandbytes>=0.43.1\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Python/PyVenvRunner.cs:line 220
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.PostInstallAsync(InstalledPackage installedPackage, IEnumerable`1 installedDirs, IProgress`1 progress, CancellationToken cancellationToken) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/ComfyUI.cs:line 609
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.PostInstallAsync(InstalledPackage installedPackage, IEnumerable`1 installedDirs, IProgress`1 progress, CancellationToken cancellationToken) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/ComfyUI.cs:line 613
   at StabilityMatrix.Core.Models.Packages.ComfyUI.ComfyExtensionManager.UpdateExtensionAsync(InstalledPackageExtension installedExtension, InstalledPackage installedPackage, PackageExtensionVersion version, IProgress`1 progress, CancellationToken cancellationToken) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/Packages/ComfyUI.cs:line 536
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IReadOnlyList`1 steps) in /Users/runner/work/StabilityMatrix/StabilityMatrix/StabilityMatrix.Core/Models/PackageModification/PackageModificationRunner.cs:line 35

**Comment by DevopsDood** [comment]
just clone it into your custom_nodes dir
