### ISSUE TITLE
i got  this issus about ComfyUI_omost.omost_nodes - ERROR

### ISSUE THREAD

**Issue by zmczmc123654** [huchenlei/ComfyUI_omost#52]
2024-08-01 15:04:35,002 - ComfyUI_omost.omost_nodes - ERROR - Failed to import ComfyUI_densediffusion. Make sure it's installed.https://github.com/huchenlei/ComfyUI_densediffusion
Failed to import ComfyUI_densediffusion. Make sure it's installed.https://github.com/huchenlei/ComfyUI_densediffusion
!!! Exception during processing!!! No module named 'custom_nodes.ComfyUI_densediffusion'
Traceback (most recent call last):
  File "D:\SDAI\ComfyUI-aki-v1.3\execution.py", line 149, in recursive_execute
    obj = class_def()
  File "D:\SDAI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_omost\omost_nodes.py", line 474, in __init__
    raise e
  File "D:\SDAI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_omost\omost_nodes.py", line 465, in __init__
    from custom_nodes.ComfyUI_densediffusion.densediffusion_node import (
ModuleNotFoundError: No module named 'custom_nodes.ComfyUI_densediffusion'

**Comment by HiyungXu** [comment]
u need install node comfyui_densediffusion
